CREATE TABLE IF NOT EXISTS "words" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "word" TEXT NOT NULL UNIQUE,
    PRIMARY KEY("id")
);


INSERT INTO "words" ("word") VALUES
('abcd'),
('bcde'),
('cdef'),
('defg'),
('efgh');